version: '3.7'
services:
  jenkins:
    build:
      context: .
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.footerURL=http://yallalabs.com
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    ports:
      - 9001:8080
      - 50000:50000
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - financial_portfolio_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

networks:
  financial_portfolio_network:

#volumes:
#  jenkins_data:
#    driver: local
#    driver_opts:
#      type: "none"
#      o: "bind"
#      device: "/jenkinsdata"