version: '3.8'

services:
  base-service-configurations: &base-service-configurations
    build:
      context: .
    image: financial-portfolio
    networks:
      - financial_portfolio_network

  portfolio-service:
    <<: *base-service-configurations
    container_name: portfolio-service
    ports:
      - "8080:8080"
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s ./gradlew :portfolio-service:bootRun

  stocks-service:
    <<: *base-service-configurations
    container_name: stocks-service
    ports:
      - "8081:8081"
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s ./gradlew :stocks-service:bootRun
    depends_on:
      - rabbitmq

  financial-portfolio:
    image: financial-portfolio
    container_name: financial-portfolio
    depends_on:
      - portfolio-service
      - stocks-service

### DEPENDENCIES

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - financial_portfolio_network

### TEST / PROCESS RELATED DEPENDENCIES

  jenkins:
    image: jenkins/jenkins:latest-jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "9001:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JENKINS_HOME=/var/jenkins_home
    volumes:
      - /var/jenkins/caches:/var/jenkins/caches
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    networks:
      - financial_portfolio_network

  wiremock:
    build:
      dockerfile: tools/wiremock/Dockerfile
    #container_name: wiremock
    command: java -jar lib/wiremock-jre8-standalone.jar --port 8080 --local-response-templating --max-request-journal-entries 1000 --root-dir .
    ports:
      - "9002:8080"
    networks:
      - financial_portfolio_network

networks:
  financial_portfolio_network: